.github/workflows/integration-tests.yml
freelens/package.json

Without extra suid for `chrome-sandbox` integration tests break on Ubuntu with error:
> The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/runner/work/freelens/freelens/freelens/dist/linux-unpacked/chrome-sandbox is owned by root and has mode 4755.
It looks like regression introduced by some update in Github Actions ubuntu-latest.
TODO: The same fix for https://github.com/freelensapp/freelens-node-pod-menu

Fix integration tests on Ubuntu (chrome-sandbox)

---

.github/workflows/release.yml
LICENSE
freelens/package.json

It'll be used when `npm run build:app -- -- -- pkg` runs.

Extra setttings for MacOS PKG

---

packages/core/src/features/application-menu/main/menu-items/special-menu-for-mac-application/show-about-application/show-about.injectable.ts

Fixes #44 
The original listing of all modules was too verbose and causes that "Close" button was not visible on Linux (Ubuntu with Gnome).

Less verbose About window

---

.github/workflows/compute-versions.yaml

It should run checks now.
Also it tweaks the message of PR and adds the label.

Fix for automated updates of kubectl versions

---

.github/workflows/compute-versions.yaml

Some solution might be using a dedicated author of the commit.
Updates of kubectl versions are potentially safe, so maybe we can leave the PRs unchecked.

Push by github_actions won't trigger checks

---

LICENSE
README.md
license-header

Currently Github shows that license is Unknown
Using https://github.com/licensee/licensee:
Before:
```
License:        NOASSERTION
Matched files:  LICENSE, license-header, README.md
LICENSE:
Content hash:  176490e49c30fdcd4d93c0b15bc87cc239054307
License:       NOASSERTION
Closest non-matching licenses:
MIT similarity:    93.47%
MIT-0 similarity:  72.10%
NCSA similarity:   59.66%
license-header:
Content hash:  5419233269643fcfb748d1a4464de95798b9bc5f
License:       NOASSERTION
Closest non-matching licenses:
WTFPL similarity:  3.85%
0BSD similarity:   1.96%
ISC similarity:    1.74%
README.md:
Content hash:  132a12043d3270343cc41b39fa8bc2552e779c96
Confidence:    90.00%
Matcher:       Licensee::Matchers::Reference
License:       MIT
Closest non-matching licenses:
WTFPL similarity:  11.11% …
```

License document that should be detected correctly by Github

---

.github/workflows/release.yml

Synced with the latest freelens-nightly-build repo

Tweaks for Release workflow

---

freelens/build/notarize.js

The default setting causes:
```
• signing         file=dist/mac/Freelens.app identityName=Developer ID Application: *** (TFR6NT55MB) identityHash=83CA6BAC095C2A693F3AE78ED335D80C58CE2059 provisioningProfile=none
⨯ Failed to upload app to Apple's notarization servers
2024-11-03 20:33:41.632 *** Error: Unable to upload your app for notarization.
2024-11-03 20:33:41.633 *** Error: Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (-1031)
failedTask=build stackTrace=Error: Failed to upload app to Apple's notarization servers
```
It doesn't make sense to keep the current setting as the default as it is not possible to use it anymore.

CI: notarytool must be now the default as altool has been decommissioned

---

packages/core/src/extensions/install-extension/install-extension.injectable.ts

Use the current environment in forked process

---

LICENSE-binaries
freelens/package.json

Now Github again does not recognize our license so the extra file is just for binaries.

Separate license file for binaries

---

.github/workflows/release.yaml

It is to avoid rejection my Notarization service when 2 requests are sent in the same time.

Do not run 2 macos jobs in the same time

---

README.md

The previous link would just point to the current repository of freelens, https://github.com/freelensapp/freelens, instead of the extension repository https://github.com/freelensapp/freelens-node-pod-menu.

docs: fix link for freelens-node-pod-menu in README

---

freelens/build/apparmor-profile.aa

This is based on the other profiles on Ubuntu 24.04 (ie. chromium).
It is still not to run as enforced hovewer the application should be detected with a separate profile.

Fixes for apparmor profile

---

packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
packages/core/src/renderer/components/extensions/extensions.tsx

This is a recommendation of `@freelensapp/freelens-node-pod-menu` so it should be easier to install it by new users.

Added advertisement of @freelensapp/freelens-node-pod-menu

---

README.md
freelens/build/metainfo.xml

FIxes incorrect `<launchable>` tag as it was discovered in https://buildbot.flathub.org/#/builders/6/builds/177149:
```json
{
"errors": [
"metainfo-launchable-tag-wrong-value"
],
"info": [
"metainfo-launchable-tag-wrong-value: The value of launchable tag in Metainfo is wrong: app.freelens.Freelens"
],
"message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

Fix for incorrect launchable tag in metainfo file

---

.github/workflows/release.yaml

After testing it with nightly builds I'm porting it to the main repo.
It fixes #108

Sign Windows MSI and EXE

---

packages/core/src/features/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
packages/core/src/features/cluster/namespaces/edit-namespace-from-new-tab.test.tsx
packages/core/src/renderer/components/dock/edit-resource/edit-resource-model/edit-resource-model.injectable.tsx

Fixes #141
- Replaces label with annotation
- Renamed to keep convention `foo.domain.name/something`

Use annotation rather than label for marking manual edits

---

packages/core/src/common/cluster-types.ts
packages/core/src/main/routes/metrics/add-metrics-route.injectable.ts
packages/core/src/renderer/components/cluster-settings/prometheus-setting.tsx
packages/technical-features/prometheus/src/helm-provider.injectable.ts
packages/technical-features/prometheus/src/lens-provider.injectable.ts
packages/technical-features/prometheus/src/operator-provider.injectable.ts.ts
packages/technical-features/prometheus/src/stacklight-provider.injectable.ts

Defining the mountpoints per cluster for the filesystem metrics

---

packages/core/src/common/cluster-types.ts
packages/core/src/main/shell-session/node-shell-session/node-shell-session.ts
packages/core/src/renderer/components/cluster-settings/node-shell-setting.tsx
packages/kube-object/src/specifics/node.ts

This is a reworked node-shell feature. It allows to run it on Bottlerocket OS and Windows nodes where there is no `sh` nor `bash` command.
Unfortunately, node-shell pods cannot be autoremoved anymore with `sleep` command. It is because now single pod is created and then `kubectl attach` is run. It is because `kubectl exec` with `nsenter` command won't work: Bottlerocket OS is SELinux hardened then `nsenter` won't have privileges to run in `kubectl exec` context.
Bottlerocket OS:
Windows 2022:

Allows to run node shell on Bootlerocket and Windows nodes

---

packages/core/src/renderer/components/__tests__/cronjob.store.test.ts
packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/implementations/cron-job-detail-item.injectable.ts
packages/resource-templates/templates/create-resource/CronJob.yaml

PR taken from https://github.com/tanoggy/lens/tree/change-apiversion-cronjob by @tanoggy

Updated apiVersion for CronJobs from batch/v1beta1 to batch/v1

---

package-lock.json

Forced update for serialize-javascript with fixed CVE-2024-11831

Update dependency serialize-javascript to v6.0.2

---

package.json
packages/core/src/renderer/components/cluster-manager/cluster-frame-handler.ts
patches/monaco-editor+0.52.2.patch

Fixes #445, #434
- Added security context for iframe that enabled read-write operations on clipboard
- Patch for VS Code (monaco-editor) which enables alternative clipboard handler on newer Chrome

Fix for problem that paste operation doesn't work in an editor

---

packages/core/src/renderer/components/app.scss

Removed custom text selection styling that was causing readability issues in the light theme, where selected text would become invisible (white text on white background). This change follows the behavior already implemented in the Lens application.

Remove text selection style causing readability issues in light theme

---

packages/ui-components/error-boundary/src/error-boundary.tsx

There was no space between these words and the link.
Didn't see any tests for this file, but it fixed it locally.

Fix spacing issue in error boundary

---

packages/core/src/features/application-menu/main/menu-items/view/go-back/go-back-menu-item.injectable.ts
packages/core/src/features/application-menu/main/menu-items/view/go-forward/go-forward-menu-item.injectable.ts
packages/core/src/main/ipc/window.ts
packages/core/src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts

Fixes #490
- These APIs have been moved to the navigationHistory property of WebContents to provide a more structured and intuitive interface for managing navigation history.

Replaced deprecated navigation-related APIs in Electron

---

packages/core/src/main/catalog-sources/kubeconfig-sync/watch-file-changes.injectable.ts

Ignores files that are for sure not a kube config files.

More file patterns are ignored during scanning kube folder, including kubectx and kubens caches

---

packages/core/src/main/routes/metrics/add-metrics-route.injectable.ts

Full stack trace kills the output.

Less verbose warning about no Prometheus service found

---

.github/workflows/integration-tests.yaml
.github/workflows/release.yaml
DEVELOPMENT.md
freelens/package.json
freelens/src/common/application-information.injectable.ts

Fix for errors in the workflow for integration tests.
On Windows electron-build tries to publish the package.

Disable publishing and updating

---

packages/core/src/features/hotbar/hovering-hotbar-menu.test.ts
packages/core/src/renderer/components/catalog/__tests__/catalog-add-button.test.tsx
packages/ui-components/tooltip/src/tooltip.test.tsx
packages/ui-components/tooltip/src/withTooltip.test.tsx

These tests are flacky and breaks too often. This change might help or they'll be skipped.

Tests: skipping flaky tests with hovering on the components

---

README.md

This enables us to install the Freelens app using the `scoop` command. See [#15193](https://github.com/ScoopInstaller/Extras/pull/15193)

Readme: Scoop package for Windows [skip ci]

---

.github/workflows/integration-tests.yaml
.github/workflows/kubectl-versions.yaml
.github/workflows/linter.yaml
.github/workflows/npm-audit.yaml
.github/workflows/npm-dedupe.yaml
.github/workflows/npm-version.yaml
.github/workflows/release.yaml
.github/workflows/trunk-upgrade.yaml
.github/workflows/unit-tests.yaml

Replaces action for retries with native syntax because messages from nick-fields/retry are folded and native syntax is more friendly to browse.

CI: replace nick-fields/retry@v3 with retry task

---

packages/core/package.json
pnpm-lock.yaml

The package is now deprecated.

Remove @types/react-virtualized-auto-sizer

---

freelens/electron-builder.yml

Fixes https://github.com/freelensapp/freelens-nightly-builds/actions/runs/14850771633/job/41693805278
- electron is added to ASAR even if it is in devDependencies but we can exclude it explicitely
- more tweaks for files in ASAR

Remove electron from ASAR explicitely

---

package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Fixes https://github.com/freelensapp/freelens/security/code-scanning/83 and https://github.com/freelensapp/freelens/security/code-scanning/82
- Forces update of http-proxy-middleware to v3

Override update http-proxy-middleware to v3

---

packages/core/src/common/catalog-entities/general-catalog-entities/implementations/catalog-catalog-entity.injectable.ts
packages/core/src/common/catalog-entities/general-catalog-entities/implementations/welcome-catalog-entity.injectable.ts
packages/core/src/features/preferences/common/preferences-catalog-entity.injectable.ts
packages/core/src/renderer/components/layout/sidebar-items.module.scss
packages/core/src/renderer/themes/lens-light.injectable.ts

Hi! A few UI fixes for `Light` theme:
* primary color hex
* sidebar subMenu active state
* use primary for global icons

Modify light theme for primary and sub menu active state colors

---

knip.jsonc
package.json
pnpm-lock.yaml

If pnpm is used as alias `corepack pnpm` then running another pnpm from the package.json causes error like "command not found".
We have already pnpm in runtime dependencies then it is not a problem to add them into root as devDependencies.

Add pnpm as a dependency for root workspace

---

packages/core/src/renderer/components/workloads-pods/columns/pods-memory-usage-column.injectable.tsx
packages/core/src/renderer/components/workloads-pods/pods.scss
packages/utility-features/utilities/src/convert-memory.test.ts
packages/utility-features/utilities/src/convertMemory.ts

Also strips "B" and the end so all numbers are aligned. It saves also space and shows more important value in smaller screens.
Follow up #776
FYI @HanCheo

Align memory and CPU usage in pods table

---

packages/core/src/features/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
packages/core/src/main/helm/repositories/get-active-helm-repositories/get-active-helm-repositories.injectable.ts

Handles the case when
```
$ helm repo update
Error: no repositories found. You must add one before updating
```
In that case we don't add any repo anymore then we should return empty array with repos.

Bugfix when helm repo update shows no repositories found

---

packages/core/src/extensions/renderer-api/components.ts
packages/core/src/renderer/components/kube-object/index.ts

KubeObjectAge is missing in API and adding it in extensions takes a lot of unecessary code.

Provide KubeObjectAge in Extensions API

---

packages/core/src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts

Fixes:
```
warn:    ┏ [getPortFrom]: failed to retrieve port via starting to serve on (?<address>.+) +467ms
warn:    ┃ [1] {
warn:    ┃ [2]   '0': "~~ Freelens K8s Proxy, '1.3.2-SNAPSHOT-fb71c44' ~~\n" +
warn:    ┃ [3]     'kubeconfig: /Users/dex4er/.kube/config\n' +
warn:    ┃ [4]     'api prefix: /6595b4740c230fa2/\n' +
warn:    ┃ [5]     'kubeconfig context: kind-test\n' +
warn:    ┃ [6]   timestamp: '08/06/2025 22:28:09'
warn:    ┗ [7] }
(node:67302) UnhandledPromiseRejectionWarning: Error: failed to retrieve port from stream
at Timeout._onTimeout (/Users/dex4er/Sources/freelens/freelens/freelens/dist/mac-arm64/Freelens.app/Contents/Resources/app.asar/node_modules/@freelensapp/core/static/build/library/main.js:42459:28)
at listOnTimeout (node:internal/timers:588:17)
at …
```

Restart proxy if port is not found

---

packages/core/src/common/k8s-api/kube-object.store.ts
packages/utility-features/kube-api/src/kube-api.ts

Fixes #847
- Removes `evict` from default APIs and leaves it only for pods API.
- Removing resources calls `delete` instead of `evict`.

Use standard delete rather than eviction for removing pods

---

.trunk/trunk.yaml

- plugins v1.7.1
- yamlfmt is in upstream
- `${root_or_parent_with_any_config}` for biome
- renovate tag for node

Manual trunk upgrade trunk-io/plugins v1.7.0 → v1.7.1

---

packages/technical-features/prometheus/src/operator-provider.injectable.ts.ts

freelens doesn't calculate the pod cpu, memory and filesystem usage correctly. Here's an example of a single-container pod:
Before:
After:
I have this issue with those metrics: 
```
container_cpu_usage_seconds_total
container_memory_working_set_bytes
container_fs_usage_bytes
container_fs_writes_bytes_total
container_fs_reads_bytes_total
```
Those are all metrics where the name starts with `container_*`, excluding `container_network_*` (Those never have a `container` attribute).
All other `*-provider.injectable.ts` have this same fix applied. I haven't been able to find why this one is different, so let's set them to the same queries.
**Info about my cluster**
I'm running k3s, with one master node and multiple "worker" nodes.  
Prometheus is provided by the `bitnami/kube-prometheus` helm …

Prometheus graphs ignores metrics with empty container label

---

packages/core/src/renderer/components/__tests__/cronjob.store.test.ts
packages/core/src/renderer/components/__tests__/deployments.store.test.ts
packages/core/src/renderer/components/workloads-deployments/scale/dialog.test.tsx
packages/core/src/renderer/components/workloads-pods/details/containers/pod-details-ephemeral-containers.tsx
packages/core/src/renderer/components/workloads-pods/pod-details-container.tsx
packages/core/src/renderer/components/workloads-pods/pod-details.tsx
packages/kube-object/src/specifics/pod.ts
packages/kube-object/src/types/ephemeral-container.ts
packages/kube-object/src/types/index.ts

Closes #184
Terminating the ephemeral container is tricky as Kubernetes does not hold information about the main PID for containers with shared PIDs. The workaround might be either adding some information about main PID to logs or using cgroups to find out the main PID to kill.
Creating/killing the containers will be in a separate PR.

Add ephemeral containers to pods view

---

packages/core/src/renderer/components/kube-object-menu/kube-object-menu-items/cron-job-menu.injectable.ts
packages/core/src/renderer/components/kube-object-menu/kube-object-menu-items/job-menu-copy.injectable.ts

- Removed API batch/v1beta1
New CronJob view is not backward compatible and it would take too much effort to support old, long forgotten API. Sorry!

API batch/v1beta1 is not supported anymore

---

packages/core/src/renderer/components/workloads-cronjobs/cronjobs.tsx

Casting to the correct types in sortable columns for CronJobs list view.
Maybe it will fix the crashes.

Fix CronJobs list for sorting

---

packages/core/src/common/k8s-api/kube-object.store.ts

Must be optional for backward compatibility

Regression: patch 3rd argument has to be optional

---

packages/core/src/common/k8s-api/kube-object.store.ts
packages/core/src/extensions/common-api/k8s-api.ts

The object was already used in FluxCD extension and has static methods `getStore` and `getApi` and additional property with metainfo for CRDs.

API exports new LensExtensionKubeObject class

---

pnpm-lock.yaml
pnpm-workspace.yaml

See https://github.com/freelensapp/freelens/security/code-scanning/88
and CVE-2025-7339
used by `webpack-dev-server@5.2.2(webpack-cli@6.0.1)(webpack@5.100.2)`

Override dependency compression to ^v1.8.1

---

packages/core/src/renderer/components/workloads-cronjobs/cronjob-details.tsx

As Freenlens users I felt useful to provide this small contribution regarding the Cronjob details page
In particular here we have the following small changes:
* The list of Cronjob executions is now sorted by descending `startTime`
* Each element in the list is now identified by the job unique name and not using the general Cronjob name
* Each element in the list now shows also the `Start Date` and the `Duration`
Hope these changes could be useful also for other users.

Include more details for the Cronjobs executions

---

packages/core/src/renderer/components/custom-resource-definitions/details.tsx
packages/kube-object/src/specifics/custom-resource-definition.ts

- All versions are presented
- The preferred version is marked
- API has a new method `getVersions()`

Show all versions of CRDs

---

packages/core/src/renderer/components/custom-resources/details.scss

- Ready state is peferred before others
"Ready" is more dark so other statuses should not "depromote" it

CSS tweaks for condition badges

---

packages/core/src/renderer/components/custom-resources/__tests__/__snapshots__/custom-resource-details.test.tsx.snap
packages/core/src/renderer/components/custom-resources/details.tsx
packages/core/src/renderer/components/custom-resources/view.tsx
packages/core/src/renderer/components/nodes/details-resources.tsx

- `startCase` for printable columns

Use spaces for printable columns for CRDs

---

packages/core/src/renderer/components/drawer/drawer-item.scss
packages/core/src/renderer/components/drawer/drawer-item.tsx

- Renders auto column if DrawerItem hasn't a name

CSS fix for DrawerItem without name

---

packages/core/src/extensions/renderer-api/components.ts
packages/core/src/extensions/renderer-api/navigation.ts
packages/core/src/renderer/components/kube-detail-params/get-maybe-details-url.injectable.ts
packages/core/src/renderer/components/kube-object-link/index.ts
packages/core/src/renderer/components/kube-object-link/link-to-cluster-role.tsx
packages/core/src/renderer/components/kube-object-link/link-to-namespace.tsx
packages/core/src/renderer/components/kube-object-link/link-to-object.tsx
packages/core/src/renderer/components/kube-object-link/link-to-role.tsx
packages/core/src/renderer/components/kube-object-link/link-to-secret.tsx
packages/core/src/renderer/components/kube-object-link/link-to-service-account.tsx
packages/core/src/renderer/components/user-management/cluster-role-bindings/details.tsx
packages/core/src/renderer/components/user-management/cluster-role-bindings/view.tsx
packages/core/src/renderer/components/user-management/role-bindings/details.tsx
packages/core/src/renderer/components/user-management/role-bindings/view.tsx
packages/kube-object/src/specifics/cluster-role-binding.ts
packages/kube-object/src/specifics/role-binding.ts

- Added the column with (cluster) role name and binding types (Kind)
- Lists are hyperlinked
- Details too
- New components simplify linking. All they started with `<LinkTo...>` and will be used later in other views.

Columns with role name and ref types in RBAC bindings

---

packages/core/src/common/catalog-entities/kubernetes-cluster.ts
packages/core/src/common/cluster-types.ts
packages/core/src/main/cluster/prometheus-handler/prometheus-handler.ts
packages/core/src/renderer/components/cluster-settings/prometheus-setting.tsx

Fixes #1132
This PR adds explicit HTTPS support and a custom path prefix to Prometheus settings.
What
- Add `https?: boolean` to Prometheus preferences and related cluster metrics types
- Respect HTTPS in service-proxy paths by prefixing services with `https:` per K8s API conventions
- Prometheus settings UI improvements:
- Add an explicit HTTPS toggle
- Add a separate custom path prefix field (auto-sanitized to start with a leading slash)
- Persist all settings cohesively on blur/change
- Default behavior remains unchanged (HTTP, no prefix) for backward compatibility
Why
Externally hosted Prometheus deployments often require HTTPS and a path prefix (e.g., `/prometheus`). Previously this had to be encoded implicitly and assumed HTTP, making configuration error-prone. This change makes the …

Add HTTPS support and custom prefix in Prometheus settings

---

packages/core/src/renderer/components/workloads-pods/pod-details-list.tsx

Fixes #1129
- Hides node column if owner of the component is node already.

Hide node column if pod list is shown in node details

---

packages/core/src/renderer/components/kube-object-link/index.ts
packages/core/src/renderer/components/kube-object-link/link-to-job.tsx
packages/core/src/renderer/components/workloads-cronjobs/cronjob-details.scss
packages/core/src/renderer/components/workloads-cronjobs/cronjob-details.tsx
packages/core/src/renderer/components/workloads-cronjobs/cronjobs.scss
packages/core/src/renderer/components/workloads-cronjobs/cronjobs.tsx
packages/core/src/renderer/components/workloads-jobs/job-details.tsx
packages/core/src/renderer/components/workloads-jobs/jobs.scss
packages/core/src/renderer/components/workloads-jobs/jobs.tsx

- The field is renamed from "Suspend" to "Resumed" so if it is active then it should be green by default as True that means it is all healthy and running.

Field name renamed from Susped to Resumed for Jobs and CronJobs

---

packages/core/src/renderer/components/kube-object-conditions/components.tsx
packages/core/src/renderer/components/kube-object-conditions/kube-object-conditions-list.tsx
packages/core/src/renderer/components/nodes/nodes.scss
packages/core/src/renderer/components/nodes/route.tsx

Fixes #1196
- Presents Ready or NotReady as the first condition on the list
- Separte column for Schedulable/Unschedulable status
Either NotReady or ScheduledDisabled are not real conditions. NotReady is just "Ready" if state is unknown or error. To not list all failed conditions only "Ready" is presented for negation.
ScheduledDisabled is added if `spec.unschedulable === true`. Because I prefer condition list for real conditions (NotReady is actually real condition even if negated) then schedulable will be yet another column.

Presents Ready/NotReady first on the conditions list

---

pnpm-lock.yaml
pnpm-workspace.yaml

Fixes https://github.com/freelensapp/freelens/security/code-scanning/86
- Updated dependency

Forced update dependency minimatch to ^5.0.0

---

.github/workflows/release.yaml

- Disables pre/post scripts as workflow explicitly calls them and they break on cross-compile environment

Disable pre/post scripts in release workflow
