open-lens/package.json, packages/core/src/main/__test__/kube-auth-proxy.test.ts, packages/core/src/main/kube-auth-proxy/create-kube-auth-proxy.injectable.ts, packages/core/src/main/kube-auth-proxy/freelens-k8s-proxy-path.injectable.ts, packages/ensure-binaries/src/index.ts
I renamed where necessary and tested the build.
=> Use freelens-k8s-proxy

packages/core/src/renderer/components/network-ingresses/ingresses-sidebar-items.injectable.ts
Fixes wrong route after clicking Ingresses in sidecar menu.
Fixes #5
=> Fixes click on Ingresses in sidebar

.github/workflows/compute-versions.yaml
Correct workflow for kubectl updates
=> CI: Skip pushing/PR if no changes

.github/workflows/compute-versions.yaml, .github/workflows/integration-tests.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml, freelens/package.json
=> Custom Exec entry in Desktop file

.github/workflows/osv-scanner.yaml
As we do not use dependabot, we can do scans with separate action.
=> Github Action for OSV-Scanner

.github/workflows/npm-version.yaml, .github/workflows/release.yaml
Fixes #10
The final pipeline for the release.
=> Sync release pipeline with the latest nightly

freelens/package.json
=> Add libasound2 and libgbm1 to Debian package

.github/workflows/release.yaml
=> Monkey patch FPM arguments to fix bug for RPM aarch64

freelens/package.json
=> More dependencies for RPM

freelens/package.json
It looks like our APT repository really works then it might be added to the DEB package then the package will be always autoupgraded.
=> APT repository added to the DEB package

.github/workflows/npm-version.yaml, freelens/build/app.freelens.Freelens.metainfo.xml, freelens/package.json
=> Include AppData metainfo in the binary packages

packages/core/src/renderer/components/extensions/attempt-install/unpack-extension.injectable.tsx
=> Wrong plugin installation never ends

packages/core/src/renderer/components/node-pod-menu/__tests__/node-menu.test.tsx, packages/core/src/renderer/components/node-pod-menu/__tests__/pod-attach-menu.test.tsx, packages/core/src/renderer/components/node-pod-menu/__tests__/pod-logs-menu.test.tsx, packages/core/src/renderer/components/node-pod-menu/__tests__/pod-menu-item.test.tsx, packages/core/src/renderer/components/node-pod-menu/__tests__/pod-shell-menu.test.tsx, packages/core/src/renderer/components/node-pod-menu/node-menu.tsx, packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/node-menu.injectable.ts, packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/pod-attach-menu.injectable.ts, packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/pod-logs-menu.injectable.ts, packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/pod-shell-menu.injectable.ts, packages/core/src/renderer/components/node-pod-menu/pod-attach-menu.tsx, packages/core/src/renderer/components/node-pod-menu/pod-logs-menu.tsx, packages/core/src/renderer/components/node-pod-menu/pod-menu-item.tsx, packages/core/src/renderer/components/node-pod-menu/pod-shell-menu.tsx, packages/core/src/renderer/components/status-brick/status-brick.scss, packages/core/src/renderer/components/workloads-pods/pods.scss
- Fixed containers status color on "Log" menu
- Added unit tests
This pull request resolve #129
=> node-pod-menu extension is a part of the main application

DEVELOPMENT.md, README.md, packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap, packages/core/src/renderer/components/extensions/extensions.tsx
=> Clean up after adapting node-pod-menu extension in a codebase

.gitignore, package-lock.json, package.json
=> Removed adr package

freelens/package.json, package-lock.json, packages/core/package.json, packages/utility-features/utilities/package.json
New tar@7 has typings included.
=> Remove dependency @types/tar

README.md, freelens/package.json
=> Add --disable-gpu-compositing argument

package-lock.json, packages/core/package.json
=> Remove unused @types/md5-file

freelens/package.json, package-lock.json
request-promise-native is unused
=> Remove unused @types/request-promise-native

package-lock.json, packages/core/package.json
=> Remove unused @types/mock-fs

.github/workflows/integration-tests.yaml, .github/workflows/release.yaml, .github/workflows/unit-tests.yaml, .gitignore
Minor improvement for unit tests and publishing
=> CI: Use cache for Electron

.github/workflows/integration-tests.yaml, .github/workflows/kubectl-versions.yaml, .github/workflows/npm-audit.yaml, .github/workflows/npm-dedupe.yaml, .github/workflows/npm-version.yaml, .github/workflows/release.yaml, .github/workflows/tag.yaml, .github/workflows/trunk-upgrade.yaml, .github/workflows/unit-tests.yaml, .trunk/trunk.yaml, .yamlfmt.yaml, packages/resource-templates/templates/.yamlfmt.yaml, packages/resource-templates/templates/create-resource/ClusterRole.yaml, packages/resource-templates/templates/create-resource/ConfigMap.yaml, packages/resource-templates/templates/create-resource/Job.yaml, packages/resource-templates/templates/create-resource/PersistentVolume.yaml, packages/resource-templates/templates/create-resource/PersistentVolumeClaim.yaml, packages/resource-templates/templates/create-resource/Pod.yaml, packages/resource-templates/templates/create-resource/Service.yaml, packages/resource-templates/templates/create-resource/StatefulSet.yaml
I'm going to remove prettier then we must format YAML files somehow.
Trunk Check does the work even if there is no official plugin for it yet.
=> Linter: format YAML files with yamlfmt

packages/core/src/extensions/extension-discovery/is-compatible-extension/is-compatible-extension.ts, packages/core/src/features/application-update/__snapshots__/hiding-preference-when-disabled.test.ts.snap, packages/core/src/features/application-update/child-features/application-update-using-application-menu/application-update-using-application-menu.test.ts, packages/core/src/features/application-update/child-features/application-update-using-application-menu/main/check-for-updates-menu-item.injectable.ts, packages/core/src/features/application-update/child-features/application-update-using-top-bar/renderer/update-application-top-bar-item/update-button/update-button.tsx, packages/core/src/features/application-update/child-features/application-update-using-tray/installing-update-using-tray.test.ts, packages/core/src/features/application-update/child-features/application-update-using-tray/main/tray-items/check-for-updates-tray-item.injectable.ts, packages/core/src/features/cluster/delete-dialog/__snapshots__/delete-cluster-dialog.test.tsx.snap, packages/core/src/features/preferences/__snapshots__/closing-preferences.test.tsx.snap, packages/core/src/features/preferences/__snapshots__/extension-adding-preference-tabs.test.tsx.snap, packages/core/src/features/preferences/__snapshots__/hiding-of-empty-branches.test.tsx.snap, packages/core/src/features/preferences/__snapshots__/navigation-to-application-preferences.test.tsx.snap, packages/core/src/features/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap, packages/core/src/features/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap, packages/core/src/features/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap, packages/core/src/features/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap, packages/core/src/features/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap, packages/core/src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap, packages/core/src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap, packages/core/src/features/preferences/renderer/preference-items/application/start-up/start-up.tsx, packages/core/src/features/preferences/renderer/preference-items/proxy/allow-untrusted-certificates/allow-untrusted-certificates.tsx, packages/core/src/features/preferences/renderer/preference-items/terminal/terminal-theme/terminal-theme.tsx, packages/core/src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap, packages/core/src/main/lens-proxy/lens-proxy-port.injectable.ts, packages/core/src/main/lens-proxy/lens-proxy.ts, packages/core/src/main/start-main-application/runnables/setup-lens-proxy.injectable.ts, packages/core/src/renderer/components/delete-cluster-dialog/view.tsx, packages/core/src/renderer/themes/default-theme.injectable.ts, troubleshooting/custom-prometheus.md
Fixes #635
Rebranding for:
- texts in settings
- error messages
=> Rebranding for error messages and settings

.github/workflows/knip.yaml, .github/workflows/unit-tests.yaml
- It is better to not fail unit tests if Knip will report something and vice-versa.
=> CI: separate workflow for Knip

freelens/integration/__tests__/extensions.tests.ts
=> Test @freelensapp/extension-example installation

packages/core/src/common/fetch/fetch.injectable.ts, packages/core/src/common/fetch/proxy-fetch.injectable.ts, packages/transpilation/node-fetch/index.ts
Fixes https://github.com/freelensapp/freelens/discussions/671#discussioncomment-13065805
- Added all non-default objects to the default object.
=> Tweak transpiled version of node-fetch

README.md
This pull request updates the `README.md` file to improve the Discord badge by:
* Dynamically displaying the approximate member count of the Discord server, using a JSON-based badge that fetches data from the Discord API.
* Updating the badge URL to use the correct Discord server link.
**File(s) changed:**
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L7-R7): Enhanced the Discord badge for real-time member count and fixed the server URL.
=> Readme: Update discord badge to make it dynamic

packages/core/src/common/helm/helm-repo.ts, packages/core/src/features/helm-charts/child-features/preferences/renderer/adding-of-public-helm-repository/public-helm-repositories/request-public-helm-repositories.injectable.ts
This is the same URL that is used by `helm search hub` command.
=> Use hub.helm.sh to fetch the list of Helm repos

packages/core/src/common/k8s/resource-stack.ts, packages/core/src/common/kube-helpers.ts, packages/core/src/features/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap, packages/core/src/main/__test__/kubeconfig-manager.test.ts, packages/core/src/main/helm/helm-service/get-helm-release-resources/call-for-kube-resources-by-manifest/call-for-kube-resources-by-manifest.injectable.ts, packages/core/src/main/resource-applier/resource-applier.ts, packages/core/src/main/routes/kubeconfig-route/get-service-account-route.injectable.ts, packages/core/src/renderer/components/dock/edit-resource/edit-resource-model/edit-resource-model.injectable.tsx, packages/core/src/renderer/components/workloads-pods/pod-details-affinities.tsx
Following parameters are used everywhere:
```json
{
noArrayIndent: true,
noCompatMode: true,
noRefs: true,
quotingType: '"',
sortKeys: true
}
```
=> YAML dump with consistent formatting

freelens/integration/__tests__/extensions.tests.ts
@freelensapp/extension-example is replaced with @freelensapp/example-extension
=> Test with @freelensapp/example-extension

packages/core/src/renderer/extension-api.ts, packages/core/src/renderer/library.ts
its available as global.ReactJsxRuntime
=> Expose ReactJsxRuntime for Extensions

packages/core/src/extensions/base-extension-store.ts
Fixes #
- added getInstanceOrCreate to BaseExtensionStore
- fixes for types for createInstance and getInstance
=> getInstanceOrCreate method for extension store

CONTRIBUTING.md
There's an outdated reference to DEVELOPMENT.md, I've updated it to point to the wiki.
=> Update link to Development wiki page

packages/core/src/renderer/components/cluster/cluster-issues.tsx
Fixes #856
- Preloads namespaces then events from all namespaces
=> Preload events from all namespaces for cluster overview

packages/core/src/renderer/components/extensions/attempt-install-by-info.injectable.tsx, packages/core/src/renderer/components/extensions/install-extension-from-input.injectable.tsx
10s might be too short to download anything from npmjs.com
=> Raise timeout for installing extensions to 30s

packages/core/src/extensions/base-extension-store.ts, packages/core/src/features/persistent-storage/common/create.injectable.ts
- Fixes for Storage API to prevent casting to any
=> More Typescript fixes for Extensions API

packages/core/src/extensions/install-extension/install-extension.injectable.ts
- Sets PNPM_HOME env var so files used by PNPM are under app directory
=> pnpm manager used for installing extensions use application directory for its files

freelens/integration/helpers/utils.ts, packages/core/src/extensions/extension-discovery/extension-discovery.injectable.ts, packages/core/src/extensions/extension-discovery/extension-discovery.ts, packages/core/src/extensions/install-extension/fork-pnpm.injectable.ts, packages/core/src/extensions/install-extension/install-extension.injectable.ts, packages/core/src/features/shell-sync/main/compute-unix-shell-environment.injectable.ts, packages/core/src/features/shell-sync/main/setup-shell.injectable.ts
Fixes #
- Run pnpm install without package name before installing
- Run pnpm uninstall before files removal
=> Fix pnpm before installing. Use pnpm to uninstall.

packages/core/src/renderer/components/badge/badge-boolean.tsx, packages/core/src/renderer/components/custom-resources/__tests__/__snapshots__/custom-resource-details.test.tsx.snap
Bug after refactoring as we do not use d.ts generator for postcss :/
=> Correct class names for BadgeBoolean

freelens/electron-builder.yml
Auto updater doesn't work correctly then it is disabled metadata.
=> Explicitely disable publisher configuration for auto updater

packages/core/package.json, pnpm-lock.yaml
=> Removed unused dependency @types/glob

freelens/electron-builder.yml
Fixes #936 (maybe)
- msi.perMachine=false
=> Build MSI for user installation

packages/core/src/renderer/components/network-services/service-details.scss, packages/core/src/renderer/components/network-services/service-details.tsx, packages/kube-object/src/specifics/service.ts
Additional status details added to Load Balancer details
=> Additional details of the Service status

packages/core/src/renderer/components/status-brick/status-brick.scss, packages/core/src/renderer/components/workloads-pods/columns/pods-containers-column.injectable.tsx, packages/core/src/renderer/components/workloads-pods/container-status-class-name.tsx
Fixes #995
- Only ephemeral containers are marked as terminated if status is running but last state terminated
- Restarted containers has yellow border and are marked as "restarted".
=> Show restarted containers as green and with yellow border

packages/core/src/renderer/components/workloads-pods/pod-details-container.scss, packages/core/src/renderer/components/workloads-pods/pod-details-container.tsx, packages/core/src/renderer/components/workloads/workloads-mixins.scss
Fixes #1012
- Fixes colors of the status and brick in pod container details list
=> Fix colors in Pod container details

biome.jsonc, package.json
- It is needed by GH workflow to bump config for biome
=> Added script to migrate Biome configuration

packages/core/src/renderer/components/workloads-pods/columns/pods-containers-column.injectable.tsx, packages/core/src/renderer/components/workloads-pods/pod-details-container.tsx
- Changes ordering of the info for the status message
- Fixes tooltip
=> Fix for containers presentation in Pods list

packages/core/src/renderer/components/custom-resources/details.tsx, packages/kube-object/src/kube-object.ts
- Fixes presentation of boolean values in CRDs
- Removes overriding of printable fields as it can't work really.
=> Fix presentation of boolean values in CRDs

knip.jsonc, package.json
- Added `--no-gitignore`
- Ignored `*.d.ts`
=> Fix Knip config: ignore gitignore

packages/core/src/renderer/components/kube-object-meta/kube-object-meta.tsx
- "Deleted" field in the object details
=> Show timestamp when object was deleted

packages/core/src/renderer/components/kube-object-conditions/components.tsx, packages/core/src/renderer/components/kube-object-conditions/kube-object-conditions-drawer.tsx, packages/core/src/renderer/components/kube-object-conditions/kube-object-conditions-list.tsx
=> Reactive timestamp for condition details

packages/core/src/renderer/components/workloads-cronjobs/cronjob-details.tsx, packages/core/src/renderer/components/workloads-deployments/deployment-replicasets.tsx, packages/core/src/renderer/components/workloads-jobs/job-details.tsx, packages/core/src/renderer/components/workloads-pods/pod-details-list.tsx
- Add more tooltips: in pod lists
- Correct doubled timestamps in jobs details
=> Add more tooltips and correct timestamps

packages/core/src/renderer/components/network-ingresses/ingresses.tsx
Fixes #1029
- Only the first LB and rule are shown in the list
=> Show only the first load balancer and the rule in the ingresses list

packages/resource-templates/templates/create-resource/Deployment.yaml, packages/resource-templates/templates/create-resource/Namespace.yaml
=> Create namespace from template

freelens/package.json, packages/core/package.json, pnpm-lock.yaml
- Downgrade node-gyp to troubleshoot #1228
=> Downgrade depedency node-gyp to 11.3.0
